### ISSUE TITLE
Schedule the ODS auto update script as a cron job

### ISSUE THREAD

**Issue by cindyli** [inclusive-design/data-update-github#6]
## Is your feature request related to a problem?

New versions of the open dataset documenting COVID-19 assessment centre locations need to be automatically fetched and notify [the COVID data repo](https://github.com/inclusive-design/covid-assessment-centres/) when they are published
on the [Ontario Data Catalogue](https://data.ontario.ca/dataset/covid-19-assessment-centre-locations).

For now, [a github actions workflow](https://github.com/inclusive-design/covid-assessment-centres/actions?query=workflow%3A%22Commit+new+data+files+published+by+Ontario+Digial+Service%22) is scheduled daily to perform this task.

However, in a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. See [the Github doc](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#disabling-and-enabling-workflows).

## Describe the solution you'd like

To avoid the dependency on Github actions, [this update script](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#disabling-and-enabling-workflows) should be scheduled as a cron job on our own server or a rented server to replace the Github actions workflow. 

This cron job should run once a day.

**Comment by gtirloni** [comment]
Thanks @cindyli

**Comment by cindyli** [comment]
It's decided to use what we've had with [the Github action cron job](https://github.com/inclusive-design/covid-assessment-centres/actions/workflows/commitNewDataFile.yml) to perform the ODS auto update.
